version: "3.7"

services:
  fastapi:
    build:
      context: .
      dockerfile: config/api.Dockerfile
    entrypoint: pytest app/
    environment:
      REDIS_SERVER: redis://redis:6379
    ports:
      - "5050:8080"
    depends_on:
      - redis

  worker:
    build:
      context: .
      dockerfile: config/celery.Dockerfile
    environment:
      REDIS_SERVER: redis://redis:6379
    depends_on:
      - redis

  redis:
    image: redis:5.0.5-alpine
