version: "3.7"

services:
  fastapi:
    build:
      context: .
      dockerfile: config/api.Dockerfile
    entrypoint: uvicorn app.main:app --host 0.0.0.0 --port 8080
    environment:
      REDIS_SERVER: redis://redis:6379
    ports:
      - "5050:8080"
    depends_on:
      - redis

  worker:
    build:
      context: .
      dockerfile: config/celery.Dockerfile
    environment:
      REDIS_SERVER: redis://redis:6379
    depends_on:
      - redis

  redis:
    image: redis:5.0.5-alpine

  flower:
    image: mher/flower
    command: ["flower", "--broker=redis://redis:6379", "--port=5555"]
    ports:
      - "5555:5555"
    depends_on:
      - redis
